# Generated by Django 6.0.2 on 2026-04-19 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_remove_patient_disease_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('governorate', models.CharField(choices=[('alexandria', 'Alexandria'), ('aswan', 'Aswan'), ('asyut', 'Asyut'), ('beheira', 'Beheira'), ('beni_suef', 'Beni Suef'), ('cairo', 'Cairo'), ('damietta', 'Damietta'), ('dakahlia', 'Dakahlia'), ('fayoum', 'Fayoum'), ('gharbia', 'Gharbia'), ('giza', 'Giza'), ('ismailia', 'Ismailia'), ('kafr_el_sheikh', 'Kafr El Sheikh'), ('luxor', 'Luxor'), ('matrouh', 'Matrouh'), ('minya', 'Minya'), ('monufia', 'Monufia'), ('new_valley', 'New Valley'), ('north_sinai', 'North Sinai'), ('port_said', 'Port Said'), ('qalyubia', 'Qalyubia'), ('qena', 'Qena'), ('red_sea', 'Red Sea'), ('sharqia', 'Sharqia'), ('sohag', 'Sohag'), ('south_sinai', 'South Sinai'), ('suez', 'Suez')], max_length=50)),
                ('address', models.TextField()),
                ('medical_condition', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester_done', models.BooleanField(default=False)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonorOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='offered', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor_done', models.BooleanField(default=False)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_offers', to='accounts.donor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='donor.blooddonationrequest')),
            ],
            options={
                'unique_together': {('request', 'donor')},
            },
        ),
    ]
