# Generated by Django 6.0.4 on 2026-04-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonationrequest',
            name='condition',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=10),
        ),
    ]
