# Generated by Django 6.0.2 on 2026-02-22 15:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('donor', 'Donor')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('donor', 'Donor')], max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_pic_front', models.ImageField(upload_to='doctors/national_id_pic/front')),
                ('national_id_pic_back', models.ImageField(upload_to='doctors/national_id_pic/back')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('profile_pic', models.ImageField(upload_to='doctors/profile/')),
                ('phone_number', models.CharField(max_length=14)),
                ('excellence_certificate', models.FileField(upload_to='doctors/certificates/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_birth', models.DateField()),
                ('syndicate_card', models.FileField(upload_to='doctors/syndicate/')),
                ('practice_permit', models.FileField(upload_to='doctors/practice/')),
                ('graduation_certificate', models.FileField(upload_to='doctors/graduation/')),
                ('university', models.CharField(choices=[('cairo_university', 'Cairo University'), ('ain_shams_university', 'Ain Shams University'), ('alexandria_university', 'Alexandria University'), ('mansoura_university', 'Mansoura University'), ('future_university', 'Future University in Egypt'), ('american_university_cairo', 'The American University in Cairo'), ('zagazig_university', 'Zagazig University'), ('al_azhar_university', 'Al-Azhar University'), ('assiut_university', 'Assiut University'), ('benha_university', 'Benha University'), ('egypt_japan_university', 'Egypt-Japan University of Science and Technology'), ('kafr_el_sheikh_university', 'Kafrelsheikh University'), ('tanta_university', 'Tanta University'), ('arab_academy', 'Arab Academy for Science, Technology and Maritime Transport'), ('aswan_university', 'Aswan University'), ('beni_suef_university', 'Beni-Suef University'), ('damietta_university', 'Damietta University'), ('delta_university', 'Delta University for Science and Technology'), ('minia_university', 'Minia University'), ('new_valley_university', 'New Valley University'), ('university_sadat_city', 'University of Sadat City'), ('south_valley_university', 'South Valley University'), ('suez_canal_university', 'Suez Canal University'), ('menofia_university', 'Menofia University'), ('fayoum_university', 'Fayoum University'), ('sohag_university', 'Sohag University'), ('port_said_university', 'Port Said University'), ('british_university_egypt', 'The British University in Egypt'), ('zewail_city', 'Zewail City of Science, Technology and Innovation'), ('damanhour_university', 'Damanhour University'), ('helwan_university', 'Helwan University'), ('misr_university_science', 'Misr University for Science and Technology'), ('nile_university', 'Nile University'), ('msa_university', 'October University for Modern Sciences and Arts'), ('german_university_cairo', 'German University in Cairo'), ('galala_university', 'Galala University'), ('badr_university', 'Badr University in Cairo'), ('new_giza_university', 'New Giza University'), ('pharos_university', 'Pharos University in Alexandria'), ('sinai_university', 'Sinai University'), ('egyptian_russian_university', 'Egyptian Russian University'), ('misr_international_university', 'Misr International University'), ('october_6_university', 'October 6 University'), ('ahrarm_canadian_university', 'Ahram Canadian University'), ('canadian_international_college', 'Canadian International College'), ('mti_university', 'MTI University'), ('nahda_university', 'Nahda University in Beni Suef'), ('heliopolis_university', 'Heliopolis University'), ('egyptian_chinese_university', 'Egyptian Chinese University'), ('egyptian_elearning_university', 'Egyptian E-Learning University'), ('el_shorouk_academy', 'El Shorouk Academy'), ('french_university_egypt', 'French University of Egypt'), ('hertfordshire_egypt', 'Hertfordshire University in Egypt'), ('king_salman_university', 'King Salman International University'), ('new_mansoura_university', 'New Mansoura University'), ('toronto_metropolitan_cairo', 'Toronto Metropolitan University Cairo'), ('university_prince_edward', 'University of Prince Edward Island'), ('egypt_university_informatics', 'Egypt University of Informatics'), ('luxor_university', 'Luxor University'), ('suez_university', 'Suez University')], max_length=100)),
                ('address', models.TextField()),
                ('governorate', models.CharField(choices=[('alexandria', 'Alexandria'), ('aswan', 'Aswan'), ('asyut', 'Asyut'), ('beheira', 'Beheira'), ('beni_suef', 'Beni Suef'), ('cairo', 'Cairo'), ('damietta', 'Damietta'), ('dakahlia', 'Dakahlia'), ('fayoum', 'Fayoum'), ('gharbia', 'Gharbia'), ('giza', 'Giza'), ('ismailia', 'Ismailia'), ('kafr_el_sheikh', 'Kafr El Sheikh'), ('luxor', 'Luxor'), ('matrouh', 'Matrouh'), ('minya', 'Minya'), ('monufia', 'Monufia'), ('new_valley', 'New Valley'), ('north_sinai', 'North Sinai'), ('port_said', 'Port Said'), ('qalyubia', 'Qalyubia'), ('qena', 'Qena'), ('red_sea', 'Red Sea'), ('sharqia', 'Sharqia'), ('sohag', 'Sohag'), ('south_sinai', 'South Sinai'), ('suez', 'Suez')], max_length=50)),
                ('specification', models.CharField(choices=[('neurosurgery', 'Neurosurgery'), ('orthopedic_surgery', 'Orthopedic Surgery'), ('plastic_surgery', 'Plastic Surgery'), ('cardiothoracic_surgery', 'Cardiothoracic Surgery'), ('ent', 'Otolaryngology (ENT)'), ('vascular_surgery', 'Vascular Surgery'), ('urology', 'Urology'), ('ophthalmology', 'Ophthalmology'), ('general_surgery', 'General Surgery'), ('pediatric_surgery', 'Pediatric Surgery'), ('dermatology', 'Dermatology'), ('cardiology', 'Cardiology'), ('gastroenterology', 'Gastroenterology'), ('oncology', 'Medical Oncology'), ('hematology', 'Hematology'), ('endocrinology', 'Endocrinology'), ('nephrology', 'Nephrology'), ('rheumatology', 'Rheumatology'), ('pulmonology', 'Pulmonology'), ('neurology', 'Neurology'), ('psychiatry', 'Psychiatry'), ('emergency_medicine', 'Emergency Medicine'), ('anesthesiology', 'Anesthesiology'), ('radiology', 'Diagnostic Radiology'), ('pathology', 'Pathology'), ('internal_medicine', 'Internal Medicine'), ('pediatrics', 'Pediatrics'), ('obgyn', 'Obstetrics and Gynecology'), ('family_medicine', 'Family Medicine'), ('critical_care', 'Critical Care Medicine'), ('sports_medicine', 'Sports Medicine'), ('geriatrics', 'Geriatrics'), ('pain_medicine', 'Pain Medicine'), ('public_health', 'Public Health'), ('nuclear_medicine', 'Nuclear Medicine'), ('physical_medicine_rehab', 'Physical Medicine and Rehabilitation'), ('addiction_medicine', 'Addiction Medicine'), ('forensic_psychiatry', 'Forensic Psychiatry'), ('child_psychiatry', 'Child and Adolescent Psychiatry'), ('primary_care', 'Primary Care'), ('general_practice', 'General Practice')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_pic_front', models.ImageField(upload_to='donors/national_id/')),
                ('national_id_pic_back', models.ImageField(upload_to='donors/national_id/')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('profile_pic', models.ImageField(upload_to='donors/profile/')),
                ('phone_number', models.CharField(max_length=14)),
                ('date_of_birth', models.DateField()),
                ('last_donation_date', models.DateField()),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('address', models.TextField()),
                ('governorate', models.CharField(choices=[('alexandria', 'Alexandria'), ('aswan', 'Aswan'), ('asyut', 'Asyut'), ('beheira', 'Beheira'), ('beni_suef', 'Beni Suef'), ('cairo', 'Cairo'), ('damietta', 'Damietta'), ('dakahlia', 'Dakahlia'), ('fayoum', 'Fayoum'), ('gharbia', 'Gharbia'), ('giza', 'Giza'), ('ismailia', 'Ismailia'), ('kafr_el_sheikh', 'Kafr El Sheikh'), ('luxor', 'Luxor'), ('matrouh', 'Matrouh'), ('minya', 'Minya'), ('monufia', 'Monufia'), ('new_valley', 'New Valley'), ('north_sinai', 'North Sinai'), ('port_said', 'Port Said'), ('qalyubia', 'Qalyubia'), ('qena', 'Qena'), ('red_sea', 'Red Sea'), ('sharqia', 'Sharqia'), ('sohag', 'Sohag'), ('south_sinai', 'South Sinai'), ('suez', 'Suez')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_pic_front', models.ImageField(upload_to='nurses/national_id_pic/front')),
                ('national_id_pic_back', models.ImageField(upload_to='nurses/national_id_pic/back')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('profile_pic', models.ImageField(upload_to='nurses/profile/')),
                ('phone_number', models.CharField(max_length=14)),
                ('excellence_certificate', models.FileField(upload_to='nurses/certificates/')),
                ('date_of_birth', models.DateField()),
                ('syndicate_card', models.FileField(upload_to='nurses/syndicate/')),
                ('practice_permit', models.FileField(upload_to='nurses/practice/')),
                ('graduation_certificate', models.FileField(upload_to='nurses/graduation/')),
                ('address', models.TextField()),
                ('governorate', models.CharField(choices=[('alexandria', 'Alexandria'), ('aswan', 'Aswan'), ('asyut', 'Asyut'), ('beheira', 'Beheira'), ('beni_suef', 'Beni Suef'), ('cairo', 'Cairo'), ('damietta', 'Damietta'), ('dakahlia', 'Dakahlia'), ('fayoum', 'Fayoum'), ('gharbia', 'Gharbia'), ('giza', 'Giza'), ('ismailia', 'Ismailia'), ('kafr_el_sheikh', 'Kafr El Sheikh'), ('luxor', 'Luxor'), ('matrouh', 'Matrouh'), ('minya', 'Minya'), ('monufia', 'Monufia'), ('new_valley', 'New Valley'), ('north_sinai', 'North Sinai'), ('port_said', 'Port Said'), ('qalyubia', 'Qalyubia'), ('qena', 'Qena'), ('red_sea', 'Red Sea'), ('sharqia', 'Sharqia'), ('sohag', 'Sohag'), ('south_sinai', 'South Sinai'), ('suez', 'Suez')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('profile_pic', models.ImageField(upload_to='patients/profile/')),
                ('national_id_pic_back', models.ImageField(upload_to='patients/national_id_pic/back')),
                ('national_id_pic_front', models.ImageField(upload_to='patients/national_id_pic/front')),
                ('phone_number', models.CharField(max_length=14)),
                ('governorate', models.CharField(choices=[('alexandria', 'Alexandria'), ('aswan', 'Aswan'), ('asyut', 'Asyut'), ('beheira', 'Beheira'), ('beni_suef', 'Beni Suef'), ('cairo', 'Cairo'), ('damietta', 'Damietta'), ('dakahlia', 'Dakahlia'), ('fayoum', 'Fayoum'), ('gharbia', 'Gharbia'), ('giza', 'Giza'), ('ismailia', 'Ismailia'), ('kafr_el_sheikh', 'Kafr El Sheikh'), ('luxor', 'Luxor'), ('matrouh', 'Matrouh'), ('minya', 'Minya'), ('monufia', 'Monufia'), ('new_valley', 'New Valley'), ('north_sinai', 'North Sinai'), ('port_said', 'Port Said'), ('qalyubia', 'Qalyubia'), ('qena', 'Qena'), ('red_sea', 'Red Sea'), ('sharqia', 'Sharqia'), ('sohag', 'Sohag'), ('south_sinai', 'South Sinai'), ('suez', 'Suez')], max_length=50)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_pic_front', models.ImageField(upload_to='pharmacists/national_id/')),
                ('national_id_pic_back', models.ImageField(upload_to='pharmacists/national_id/')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('profile_pic', models.ImageField(upload_to='pharmacists/profile/')),
                ('phone_number', models.CharField(max_length=14)),
                ('pharmacy_name', models.CharField(max_length=255)),
                ('pharmacy_address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('syndicate_card', models.FileField(upload_to='pharmacists/syndicate/')),
                ('practice_permit', models.FileField(upload_to='pharmacists/practice/')),
                ('graduation_certificate', models.FileField(upload_to='pharmacists/graduation/')),
                ('university', models.CharField(choices=[('cairo_university', 'Cairo University'), ('ain_shams_university', 'Ain Shams University'), ('alexandria_university', 'Alexandria University'), ('mansoura_university', 'Mansoura University'), ('future_university', 'Future University in Egypt'), ('american_university_cairo', 'The American University in Cairo'), ('zagazig_university', 'Zagazig University'), ('al_azhar_university', 'Al-Azhar University'), ('assiut_university', 'Assiut University'), ('benha_university', 'Benha University'), ('egypt_japan_university', 'Egypt-Japan University of Science and Technology'), ('kafr_el_sheikh_university', 'Kafrelsheikh University'), ('tanta_university', 'Tanta University'), ('arab_academy', 'Arab Academy for Science, Technology and Maritime Transport'), ('aswan_university', 'Aswan University'), ('beni_suef_university', 'Beni-Suef University'), ('damietta_university', 'Damietta University'), ('delta_university', 'Delta University for Science and Technology'), ('minia_university', 'Minia University'), ('new_valley_university', 'New Valley University'), ('university_sadat_city', 'University of Sadat City'), ('south_valley_university', 'South Valley University'), ('suez_canal_university', 'Suez Canal University'), ('menofia_university', 'Menofia University'), ('fayoum_university', 'Fayoum University'), ('sohag_university', 'Sohag University'), ('port_said_university', 'Port Said University'), ('british_university_egypt', 'The British University in Egypt'), ('zewail_city', 'Zewail City of Science, Technology and Innovation'), ('damanhour_university', 'Damanhour University'), ('helwan_university', 'Helwan University'), ('misr_university_science', 'Misr University for Science and Technology'), ('nile_university', 'Nile University'), ('msa_university', 'October University for Modern Sciences and Arts'), ('german_university_cairo', 'German University in Cairo'), ('galala_university', 'Galala University'), ('badr_university', 'Badr University in Cairo'), ('new_giza_university', 'New Giza University'), ('pharos_university', 'Pharos University in Alexandria'), ('sinai_university', 'Sinai University'), ('egyptian_russian_university', 'Egyptian Russian University'), ('misr_international_university', 'Misr International University'), ('october_6_university', 'October 6 University'), ('ahrarm_canadian_university', 'Ahram Canadian University'), ('canadian_international_college', 'Canadian International College'), ('mti_university', 'MTI University'), ('nahda_university', 'Nahda University in Beni Suef'), ('heliopolis_university', 'Heliopolis University'), ('egyptian_chinese_university', 'Egyptian Chinese University'), ('egyptian_elearning_university', 'Egyptian E-Learning University'), ('el_shorouk_academy', 'El Shorouk Academy'), ('french_university_egypt', 'French University of Egypt'), ('hertfordshire_egypt', 'Hertfordshire University in Egypt'), ('king_salman_university', 'King Salman International University'), ('new_mansoura_university', 'New Mansoura University'), ('toronto_metropolitan_cairo', 'Toronto Metropolitan University Cairo'), ('university_prince_edward', 'University of Prince Edward Island'), ('egypt_university_informatics', 'Egypt University of Informatics'), ('luxor_university', 'Luxor University'), ('suez_university', 'Suez University')], max_length=100)),
                ('governorate', models.CharField(choices=[('alexandria', 'Alexandria'), ('aswan', 'Aswan'), ('asyut', 'Asyut'), ('beheira', 'Beheira'), ('beni_suef', 'Beni Suef'), ('cairo', 'Cairo'), ('damietta', 'Damietta'), ('dakahlia', 'Dakahlia'), ('fayoum', 'Fayoum'), ('gharbia', 'Gharbia'), ('giza', 'Giza'), ('ismailia', 'Ismailia'), ('kafr_el_sheikh', 'Kafr El Sheikh'), ('luxor', 'Luxor'), ('matrouh', 'Matrouh'), ('minya', 'Minya'), ('monufia', 'Monufia'), ('new_valley', 'New Valley'), ('north_sinai', 'North Sinai'), ('port_said', 'Port Said'), ('qalyubia', 'Qalyubia'), ('qena', 'Qena'), ('red_sea', 'Red Sea'), ('sharqia', 'Sharqia'), ('sohag', 'Sohag'), ('south_sinai', 'South Sinai'), ('suez', 'Suez')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
