# Generated by Django 6.0.2 on 2026-02-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_Blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
