# Generated by Django 6.0.2 on 2026-03-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='rate',
            new_name='doctor_rate',
        ),
        migrations.RenameField(
            model_name='nurse',
            old_name='rate',
            new_name='nurse_rate',
        ),
        migrations.RenameField(
            model_name='pharmacist',
            old_name='rate',
            new_name='pharmacist_rate',
        ),
    ]
