# Generated by Django 6.0.2 on 2026-02-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_blocked_alter_pendinguser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='gender',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='pharmacy_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
