# Generated by Django 6.0.2 on 2026-03-04 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_rate_doctor_doctor_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_rate',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='nurse_rate',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='pharmacist_rate',
        ),
        migrations.AddField(
            model_name='rate',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='rate',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='accounts.nurse'),
        ),
        migrations.AddField(
            model_name='rate',
            name='pharmacist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='accounts.pharmacist'),
        ),
    ]
