# Generated by Django 6.0.2 on 2026-04-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_timeslots_delete_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='disease_history',
        ),
    ]
