# Generated by Django 6.0.2 on 2026-03-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_donor_gender_alter_doctor_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='brief',
            field=models.TextField(default='doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurse',
            name='brief',
            field=models.TextField(default='nurse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='slogan',
            field=models.CharField(default='pharmacy', max_length=100),
            preserve_default=False,
        ),
    ]
