# Generated by Django 6.0.2 on 2026-02-22 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pendinguser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinguser',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='pendinguser',
            name='otp',
        ),
    ]
