# Generated by Django 6.0.2 on 2026-05-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_patient_disease_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='feedback',
            field=models.TextField(default=''),
        ),
    ]
