# Generated by Django 6.0.2 on 2026-02-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_pendinguser_attempts_remove_pendinguser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='national_id_pic_back',
            field=models.ImageField(upload_to='doctors/national_id_pic/back'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='national_id_pic_front',
            field=models.ImageField(upload_to='doctors/national_id_pic/front'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='national_id_pic_back',
            field=models.ImageField(upload_to='doctors/national_id_pic/back'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='national_id_pic_front',
            field=models.ImageField(upload_to='nurses/national_id_pic/front'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id_pic_back',
            field=models.ImageField(upload_to='patients/national_id_pic/back'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id_pic_front',
            field=models.ImageField(upload_to='patients/national_id_pic/front'),
        ),
    ]
