# Generated by Django 6.0.2 on 2026-02-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_doctor_national_id_pic_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='national_id_pic_back',
            field=models.ImageField(upload_to='nurses/national_id_pic/back'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='national_id_pic_back',
            field=models.ImageField(upload_to='pharmacists/national_id/'),
        ),
    ]
