# Generated by Django 6.0.2 on 2026-04-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0002_alter_nurserequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurserequest',
            name='nurse_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nurserequest',
            name='patient_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
