# Generated by Django 6.0.2 on 2026-04-19 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_patient_disease_history'),
        ('nurse', '0003_nurserequest_nurse_done_nurserequest_patient_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurserequest',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_requests', to='accounts.donor'),
        ),
        migrations.AlterField(
            model_name='nurserequest',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_requests', to='accounts.nurse'),
        ),
        migrations.AlterField(
            model_name='nurserequest',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_requests', to='accounts.patient'),
        ),
    ]
