# Generated by Django 6.0.2 on 2026-03-06 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('disease_description', models.TextField()),
                ('governrate', models.CharField(choices=[('alexandria', 'Alexandria'), ('aswan', 'Aswan'), ('asyut', 'Asyut'), ('beheira', 'Beheira'), ('beni_suef', 'Beni Suef'), ('cairo', 'Cairo'), ('damietta', 'Damietta'), ('dakahlia', 'Dakahlia'), ('fayoum', 'Fayoum'), ('gharbia', 'Gharbia'), ('giza', 'Giza'), ('ismailia', 'Ismailia'), ('kafr_el_sheikh', 'Kafr El Sheikh'), ('luxor', 'Luxor'), ('matrouh', 'Matrouh'), ('minya', 'Minya'), ('monufia', 'Monufia'), ('new_valley', 'New Valley'), ('north_sinai', 'North Sinai'), ('port_said', 'Port Said'), ('qalyubia', 'Qalyubia'), ('qena', 'Qena'), ('red_sea', 'Red Sea'), ('sharqia', 'Sharqia'), ('sohag', 'Sohag'), ('south_sinai', 'South Sinai'), ('suez', 'Suez')], max_length=50)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_requests', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_requests', to='accounts.patient')),
            ],
        ),
    ]
