# Generated by Django 6.0.2 on 2026-03-04 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_doctor_doctor_rate_remove_nurse_nurse_rate_and_more'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorrequest',
            name='net_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctorrequest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_requests', to='accounts.doctor'),
        ),
        migrations.AlterField(
            model_name='doctorrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_requests', to='accounts.patient'),
        ),
    ]
