# Generated by Django 6.0.2 on 2026-03-14 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_certificate'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrequest',
            name='doctor',
            field=models.ForeignKey(default='anonymous doctor', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='doctor_requests', to='accounts.doctor'),
        ),
        migrations.AlterField(
            model_name='doctorrequest',
            name='patient',
            field=models.ForeignKey(default='anonymous patient', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='doctor_requests', to='accounts.patient'),
        ),
    ]
