# Generated by Django 6.0.2 on 2026-03-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctorrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorrequest',
            old_name='governrate',
            new_name='governorate',
        ),
    ]
