# Generated by Django 6.0.2 on 2026-04-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_rename_governrate_doctorrequest_governorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorrequest',
            name='doctor_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorrequest',
            name='patient_done',
            field=models.BooleanField(default=False),
        ),
    ]
