# Generated by Django 6.0.2 on 2026-04-19 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_patient_disease_history'),
        ('doctor', '0005_add_done_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorrequest',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_requests', to='accounts.donor'),
        ),
        migrations.AlterField(
            model_name='doctorrequest',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_requests', to='accounts.doctor'),
        ),
        migrations.AlterField(
            model_name='doctorrequest',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_requests', to='accounts.patient'),
        ),
    ]
